# Generated by Django 4.1.1 on 2022-09-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tuningsheet",
            name="toe_front",
            field=models.DecimalField(decimal_places=2, default=0.05, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tuningsheet",
            name="toe_rear",
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tuningsheet",
            name="tyres_front",
            field=models.CharField(
                choices=[
                    ("Comfort: Hard (CH)", "Comfort: Hard (CH)"),
                    ("Comfort: Medium (CM)", "Comfort: Medium (CM)"),
                    ("Comfort: Soft (CS)", "Comfort: Soft (CS)"),
                    ("Sports: Hard (SH)", "Sports: Hard (SH)"),
                    ("Sports: Medium (SM)", "Sports: Medium (SM)"),
                    ("Sports: Soft (SS)", "Sports: Soft (SS)"),
                    ("Racing: Hard (RH)", "Racing: Hard (RH)"),
                    ("Racing: Medium (RM)", "Racing: Medium (RM)"),
                    ("Racing: Soft (RS)", "Racing: Soft (RS)"),
                    ("Racing: Intermediate", "Racing: Intermediate"),
                    ("Racing: Heavy Wet", "Racing: Heavy Wet"),
                    ("Dirt", "Dirt"),
                ],
                default="Comfort: Hard (CH)",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="tuningsheet",
            name="tyres_rear",
            field=models.CharField(
                choices=[
                    ("Comfort: Hard (CH)", "Comfort: Hard (CH)"),
                    ("Comfort: Medium (CM)", "Comfort: Medium (CM)"),
                    ("Comfort: Soft (CS)", "Comfort: Soft (CS)"),
                    ("Sports: Hard (SH)", "Sports: Hard (SH)"),
                    ("Sports: Medium (SM)", "Sports: Medium (SM)"),
                    ("Sports: Soft (SS)", "Sports: Soft (SS)"),
                    ("Racing: Hard (RH)", "Racing: Hard (RH)"),
                    ("Racing: Medium (RM)", "Racing: Medium (RM)"),
                    ("Racing: Soft (RS)", "Racing: Soft (RS)"),
                    ("Racing: Intermediate", "Racing: Intermediate"),
                    ("Racing: Heavy Wet", "Racing: Heavy Wet"),
                    ("Dirt", "Dirt"),
                ],
                default="Comfort: Hard (CH)",
                max_length=25,
            ),
        ),
    ]
